plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/changelog"
  - "@semantic-release/git"
  - "@semantic-release/github"

git:
  assets:
    - package.json

branches:
  - "+([0-9])?(.{+([0-9]),x}).x"
  - master