plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/changelog"
  - "@semantic-release/git"
  - "@semantic-release/github"

git:
  assets:
    - package.json
  message: "chore(release): ${nextRelease.version} [skip ci]"

branches:
  - master
  - name: dev/*
    prerelease: '${name.replace(/^dev\//g, "dev-")}'