plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/changelog"
  - "@semantic-release/git"
  - "@semantic-release/github"
#  - [
#    "@semantic-release/exec",
#    {
#      "prepareCmd": "./my-build-script.sh ${nextRelease.version}"
#    }
#  ]

git:
  assets:
    - package.json
    - package-lock.json
    - CHANGELOG.md
  message: "chore(release): ${nextRelease.version} [skip ci]"

branches:
  - master
  - name: dev/*
    prerelease: '${name.replace(/^dev\//g, "dev-")}'
  - name: feature/*
    prerelease: '${name.replace(/^feature\//g, "feature-")}'
  - name: hotfix/*
    prerelease: '${name.replace(/^hotfix\//g, "hotfix-")}'
