plugins:
  - "@semantic-release/commit-analyzer" # Аналізує коміти
  - "@semantic-release/release-notes-generator" # Генерує релізні нотатки
  - "@semantic-release/changelog" # Оновлює CHANGELOG.md
  - "@semantic-release/git" # Комітить package.json, CHANGELOG.md
  - "@semantic-release/github" # Публікує реліз на GitHub

git:
  assets:
    - package.json # Файл, який буде оновлено і закомічено
    - CHANGELOG.md # (опціонально, якщо використовуєте changelog)
  message: "chore(release): ${nextRelease.version} [skip ci]" # Коміт для оновлення файлів

branches:
  - "+([0-9])?(.{+([0-9]),x}).x" # Для старих гілок
  - master # Релізи на master