name: Deploy Develop

on:
  push:
    branches:
      - develop

jobs:

  build-image:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}

      # Set up Node.js with the latest LTS version
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      # Clean up old images
      - name: Clean up old images
        run: |
          BRANCH_NAME=$(echo "${GITHUB_REF_NAME}" | sed 's/refs\/heads\///' | sed 's/[^a-zA-Z0-9_-]/-/g')
          docker rmi -f${{ secrets.DOCKER_HUB_USERNAME }}/${GITHUB_REF_NAME}:latest || true

      # Get the current date and time
      - name: Get current date and time
        run: |
          DATE=$(date +"%d.%m.%Y-%H:%M:%S")
          echo "Current date and time: $DATE"
          echo "DATE=$DATE" >> $GITHUB_ENV

      # Build Docker Image
      - name: Build Docker Image
        run: |
          # Build the latest tag
          docker build --platform linux/amd64 -t ${{ secrets.DOCKER_HUB_USERNAME }}/${GITHUB_REF_NAME}:latest .

          # Build the versioned tag
          docker build --platform linux/amd64 -t ${{ secrets.DOCKER_HUB_USERNAME }}/${GITHUB_REF_NAME}:${DATE} .

      # Push Docker Image to Docker Hub
      - name: Push Docker Image
        run: |
          # Push the latest tag
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/${GITHUB_REF_NAME}:latest
          
          # Push the versioned tag
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/${GITHUB_REF_NAME}:${DATE}

  deploy:
    runs-on: ubuntu-latest
    needs: build-image

    steps:
      # Login to server
      - name: Login to server
        run: |
          echo "Login to server"

      # Pull docker image
      - name: Pull docker image
        run: |
          echo "Pull docker image"

      # Docker-compose down
      - name: Docker-compose down
        run: |
          echo "Docker-compose down"

      # Clean old Image
      - name: Clean old Image
        run: |
          echo "Docker-compose down"

      # Docker-compose up -d
      - name: Docker-compose up -d
        run: |
          echo "Docker-compose up -d"

      # Exit
      - name: Exit
        run: |
          echo "Exit"
