name: Build and Push Docker Image

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - develop
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build Docker Image
        run: |
          BRANCH_NAME=$(echo "${GITHUB_REF_NAME}" | sed 's/[^a-zA-Z0-9_-]/-/g')
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/node-api:${BRANCH_NAME} .

#      - name: Test Docker Compose
#        uses: cloudposse/github-action-docker-compose-test-run@main
#        with:
#          file: docker-compose.yml
#          command: up -d

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/my-node-app:latest
