name: Build and Push Docker Image

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up .env file with Docker Hub username and branch name
      - name: Set up .env file
        run: |
          echo "DOCKER_HUB_USERNAME=${{ secrets.DOCKER_HUB_USERNAME }}" >> .env.docker
          echo "BRANCH_NAME=${GITHUB_REF_NAME}" >> .env.docker  

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      # Clean up old images
      - name: Clean up old images
        run: |
          BRANCH_NAME=$(echo "${GITHUB_REF_NAME}" | sed 's/refs\/heads\///' | sed 's/[^a-zA-Z0-9_-]/-/g')
          docker rmi -f ${{ secrets.DOCKER_HUB_USERNAME }}/node-api:${BRANCH_NAME} || true

      # Build Docker Image
      - name: Build Docker Image
        run: |
          # Отримати назву гілки
          BRANCH_NAME=$(echo "${GITHUB_REF_NAME}" | sed 's/[^a-zA-Z0-9_-]/-/g')

          # Отримати версію з Git (останній тег або хеш коміту)
          VERSION=$(git describe --tags --always --dirty)

          # Створити Docker-образ з тегом: "назва-гілки:версія"
          docker build --platform linux/amd64 -t ${{ secrets.DOCKER_HUB_USERNAME }}/node-api:${BRANCH_NAME}-${VERSION} .

          # Також створити тег "latest" для зручності скачування останнього образу
          docker tag ${{ secrets.DOCKER_HUB_USERNAME }}/node-api:${BRANCH_NAME}-${VERSION} ${{ secrets.DOCKER_HUB_USERNAME }}/node-api:latest

      # Push Docker Image to Docker Hub
      - name: Push Docker Image
        run: |
          # Отримати назву гілки
          BRANCH_NAME=$(echo "${GITHUB_REF_NAME}" | sed 's/[^a-zA-Z0-9_-]/-/g')

          # Отримати версію з Git (останній тег або хеш коміту)
          VERSION=$(git describe --tags --always --dirty)

          # Push образ із тегом "назва-гілки:версія"
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/node-api:${BRANCH_NAME}-${VERSION}

          # Push тег "latest"
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/node-api:latest
#
#      # Build Docker Image
#      - name: Build Docker Image
#        run: |
#          BRANCH_NAME=$(echo "${GITHUB_REF_NAME}" | sed 's/refs\/heads\///' | sed 's/[^a-zA-Z0-9_-]/-/g')
#          docker build --platform linux/amd64 -t ${{ secrets.DOCKER_HUB_USERNAME }}/node-api:${BRANCH_NAME} .
#
#      # Push Docker Image to Docker Hub
#      - name: Push Docker Image
#        run: |
#          BRANCH_NAME=$(echo "${GITHUB_REF_NAME}" | sed 's/refs\/heads\///' | sed 's/[^a-zA-Z0-9_-]/-/g')
#          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/node-api:${BRANCH_NAME}
