name: Release
on:
  push:
    branches:
      - master # or main

permissions:
  contents: read # for checkout

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - name: Install dependencies
        run: npm clean-install

      - name: Verify the integrity of provenance attestations and registry signatures for installed dependencies
        run: npm audit signatures

      - name: Set Git user
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Get and print version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "The current version is $VERSION"  
          
      - name: Load environment variables from .env file
        run: |
          # Завантажити змінні з файлу .env
          export $(cat .env | xargs)

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npx semantic-release

#      - name: Commit version update
#        run: |
#          git config --global user.name "GitHub Actions"
#          git config --global user.email "github-actions[bot]@users.noreply.github.com"
#          git add package.json CHANGELOG.md
#          git commit -m "chore: update version after release"
#          git push